### ISSUE TITLE
Add IGV.js viewer to variant curation page

### ISSUE THREAD

**Issue by daniaki** [populationgenomics/variant-curation-portal#33]
Feature to add IGV.js viewer to the variant curation view. We will need to think about how to give the application access to gcp buckets, for example using the [OAuth feature](https://github.com/igvteam/igv.js/wiki/OAuth-Support) of the IGV.js package. Alternatively, we could use session-genreated [signed urls](https://cloud.google.com/storage/docs/access-control/signed-urls) that expire after some amount of time.

## Backend changes
- new field on the `Variant` storing path to BAMs file on GCP (JSON field might work well here to store bam path and index path)
- Update relevant views and serialiser classes to handle this new field
- Add a django management command to add bam information to existing variants in a given project
- Add OAuth token or way to generate signed urls which the front-end can use.
- Add unit tests 

## Frontend changes
- Create new `IGV` component that accepts a list of bam/bai paths to load

**Comment by cassimons** [comment]
The other option is to provision the backend with access and then proxy the requests through the portal. This is how seqr achieves this (as I understand it).  These are all tiny tiny bams, so whatever the solution is it does not need to scale to full genomes (ie we could almost just copy them to local storage).
