### ISSUE TITLE
Owners can edit all curations in a project

### ISSUE THREAD

**Issue by daniaki** [populationgenomics/variant-curation-portal#45]
context: https://centrepopgen.slack.com/archives/C046XUS8DGT/p1691967601787409

![image (1)](https://github.com/populationgenomics/variant-curation-portal/assets/7043686/1c46b03d-00d3-4e9e-98ea-ab1e04884e6d)

# Checklist
- [x] Add links to table linking out (new tab) to curation result corresponding to each row
- [x] Add "edited" tag to curation results edited by someone who is not the original assignee

**Comment by daniaki** [comment]
@SamBryen Would you prefer editing flags in-line inside the table via editable columns, or is linking to the curation result fine? If you do edit flags, would you like the curation result to be flagged as "edited" or "overridden" etc

**Comment by SamBryen** [comment]
@daniaki both are fine, which ever is easier to implement at your end.
If both are similar amounts of work, I think linking to the curation result probably does make the most sense. I can then add to the notepad why i've made what changes so we can track these edits more carefully. A "edited" tag would be great thank you!
