### ISSUE TITLE
Support GRCh38

### ISSUE THREAD

**Issue by daniaki** [populationgenomics/variant-curation-portal#48]
Recently noticed that GRCh37 is hardcoded in a few places. The app should be generalised to handle GRCh38 as well in these places.

**Comment by daniaki** [comment]
@SamBryen FYI in case the team is curating GRCh38 variants. Affected places are the [variant search page](https://curator.populationgenomics.org.au/variants/), [project list and variant results on the variant detail page](https://curator.populationgenomics.org.au/variant/1-1688598-C-CCTTCCCCCCTGCCCCG/)

**Comment by SamBryen** [comment]
Thanks @daniaki, I didn't even realise this page existed! We are exclusively curating hg19 variants for the time being, though I imagine this will change with future projects :)
