### ISSUE TITLE
Regular backups of postgres DB

### ISSUE THREAD

**Issue by EddieLF** [populationgenomics/variant-curation-portal#74]
The postgres backend for the curation portal managed by the GCP Cloud Run instance does not seem to have a backup process in place. If it doesn't, we should back the db up on a daily basis so we have something to restore from in case of data loss. 

SW team - can you confirm if there is any backing up taking place? And if not, could it be implemented?

**Comment by illusional** [comment]
@EddieLF I thought it does, are you able to let me know which postgres instance you're looking at, make sure we're looking at the same thing.

<img width="270" alt="image" src="https://github.com/user-attachments/assets/55ada47c-3d22-4b7d-949c-f9fa96e7425b">

<img width="233" alt="image" src="https://github.com/user-attachments/assets/97331eb4-5f42-47e6-882f-553558a9122d">

**Comment by EddieLF** [comment]
Thanks @illusional, you've clarified this completely. Closing this now since we do have daily backups ☑️
